### ISSUE TITLE
[5.4.0] cinnamon-settings network crashes

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/cinnamon-control-center#284]
```
 * cinnamon-control-center version 5.4.0
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Fedora 36 x86_64
 * Graphics hardware *and* driver used intel
 * 32 or 64 bit 64 bit
 ```

**Issue**

cinnamon-settings network crashes

**Steps to reproduce**

run 'cinnamon-settings network'

**Expected behaviour**

no crash

**Other information**

```
(gdb) bt full
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-vec.S:126
#1  0x00007fdc1269f562 in __GI___strdup (s=0x0) at strdup.c:41
        len = <optimized out>
        new = <optimized out>
#2  0x00007fdbe7f8e3c2 in add_details (details=0x55f23469e870, device=0x55f2344f0510, connection=0x55f2346aed30) at ../panels/network/net-device-ethernet.c:153
        ip4_config = <optimized out>
        ip6_config = 0x55f2346b1180
        ip4_address = 0x55f234785d50 "192.168.0.30"
        ip4_route = 0x55f234785d70 "192.168.0.1"
        ip4_dns = 0x55f234785d90 "192.168.0.1"
        ip6_address = 0x55f2347ae340 "fe80::e2d5:5eff:fec2:9f9a"
        ip6_route = 0x0
        ip6_dns = 0x0
        i = 0
#3  0x00007fdbe7f8f300 in populate_ui (device=0x55f2347a6070) at ../panels/network/net-device-ethernet.c:442
        c = <optimized out>
        connections = 0x55f2346bbab0 = {0x55f2346aed30}
        connection = 0x55f2346aed30
        children = <optimized out>
        l = <optimized out>
        n_connections = <optimized out>
        nm_device = <optimized out>
        state = <optimized out>
        widget = <optimized out>
        speed = <optimized out>
#4  device_ethernet_refresh_ui (device=0x55f2347a6070) at ../panels/network/net-device-ethernet.c:249
        nm_device = <optimized out>
        state = <optimized out>
        widget = <optimized out>
        speed = <optimized out>
#5  0x00007fdc12827f4c in g_object_new_internal (class=class@entry=0x55f2347284d0, params=params@entry=0x7ffdd7648410, n_params=n_params@entry=6) at ../gobject/gobject.c:2053
        nqueue = 0x55f2346afa70
        object = 0x55f2347a6070
        __func__ = "g_object_new_internal"
#6  0x00007fdc128295e5 in g_object_new_valist (object_type=<optimized out>, first_property_name=<optimized out>, var_args=var_args@entry=0x7ffdd76486e0) at ../gobject/gobject.c:2355
        params = 0x7ffdd7648410
        values = 0x7ffdd7648510

                    params_stack = {{pspec = 0x55f2343c6e80, value = 0x7ffdd7648510}, {pspec = 0x55f2343c6d30, value = 0x7ffdd7648528}, {pspec = 0x55f2343c6e10, value = 0x7ffdd7648540}, {pspec = 0x55f2343c6da0, value = 0x7ffdd7648558}, {pspec = 0x55f23477ca50, value = 0x7ffdd7648570}, {pspec = 0x55f2345f4510, value = 0x7ffdd7648588}, {pspec = 0x7a, value = 0x55f234409cc0}, {pspec = 0x7ffdd76484d0, value = 0x7fdc1269d133 <__GI___libc_free+115>}, {pspec = 0x7ffdd7648630, value = 0x7fdbe7fb1992}, {pspec = 0x79, value = 0x79}, {pspec = 0x7ffdd7648630, value = 0x7fdc12681d47 <__vasprintf_int--Type <RET> for more, q to quit, c to continue without paging--c
ernal+359>}, {pspec = 0x7fdc1269cb00, value = 0x7fdc1269d0c0 <__GI___libc_free>}, {pspec = 0xfbad8000, value = 0x7fdc12640825 <__GI_getenv+133>}, {pspec = 0x55f234409d25, value = 0x80}, {pspec = 0x7ffdd76485d0, value = 0x3}, {pspec = 0x0, value = 0x7fdc04dfed20 <g_log_structured_depth>}}
        values_stack = Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
{{g_type = 0x44 [None], data = {{v_int = 877737504, v_uint = 877737504, v_long = 94498748184096, v_ulong = 94498748184096, v_int64 = 94498748184096, v_uint64 = 94498748184096, v_float = 1.94843324e-07, v_double = 4.6688585052764714e-310, v_pointer = 0x55f234513620}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}, {g_type = 0x14 [None], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}, {g_type = 0x55f2341ff7a0 [None], data = {{v_int = 878189664, v_uint = 878189664, v_long = 94498748636256, v_ulong = 94498748636256, v_int64 = 94498748636256, v_uint64 = 94498748636256, v_float = 2.01268904e-07, v_double = 4.6688585276161437e-310, v_pointer = 0x55f234581c60}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}, {g_type = 0x44 [None], data = {{v_int = 879174752, v_uint = 879174752, v_long = 94498749621344, v_ulong = 94498749621344, v_int64 = 94498749621344, v_uint64 = 94498749621344, v_float = 2.15267846e-07, v_double = 4.6688585762859576e-310, v_pointer = 0x55f234672460}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}, {g_type = , data = {{v_int = 877593872, v_uint = 877593872, v_long = 94498748040464, v_ulong = 94498748040464, v_int64 = 94498748040464, v_uint64 = 94498748040464, v_float = 1.9280219e-07, v_double = 4.6688584981801077e-310, v_pointer = 0x55f2344f0510}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}, {g_type = 0x40 [None], data = {{v_int = 876038848, v_uint = 876038848, v_long = 94498746485440, v_ulong = 94498746485440, v_int64 = 94498746485440, v_uint64 = 94498746485440, v_float = 1.7070397e-07, v_double = 4.6688584213517141e-310, v_pointer = 0x55f234374ac0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}, {g_type = 0x10 [None], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 877669712, v_uint = 877669712, v_long = 94498748116304, v_ulong = 94498748116304, v_int64 = 94498748116304, v_uint64 = 94498748116304, v_float = 1.93879941e-07, v_double = 4.6688585019271016e-310, v_pointer = 0x55f234502d50}}}, {g_type = <error reading variable: Cannot access memory at address 0xfc0ef0f66087628>, data = {{v_int = 869810368, v_uint = 869810368, v_long = 94498740256960, v_ulong = 94498740256960, v_int64 = 94498740256960, v_uint64 = 94498740256960, v_float = 1.00700618e-07, v_double = 4.6688581136239147e-310, v_pointer = 0x55f233d840c0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}, {g_type = 0x6 [None], data = {{v_int = 1022, v_uint = 1022, v_long = 1022, v_ulong = 1022, v_int64 = 1022, v_uint64 = 1022, v_float = 1.43212703e-42, v_double = 5.0493509004975397e-321, v_pointer = 0x3fe}, {v_int = 869810368, v_uint = 869810368, v_long = 94498740256960, v_ulong = 94498740256960, v_int64 = 94498740256960, v_uint64 = 94498740256960, v_float = 1.00700618e-07, v_double = 4.6688581136239147e-310, v_pointer = 0x55f233d840c0}}}, {g_type = 0x0, data = {{v_int = 6, v_uint = 6, v_long = 6, v_ulong = 6, v_int64 = 6, v_uint64 = 6, v_float = 8.40779079e-45, v_double = 2.9643938750474793e-323, v_pointer = 0x6}, {v_int = 850, v_uint = 850, v_long = 850, v_ulong = 850, v_int64 = 850, v_uint64 = 850, v_float = 1.19110369e-42, v_double = 4.1995579896505956e-321, v_pointer = 0x352}}}, {g_type = <error reading variable: Cannot access memory at address 0x28>, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}, {g_type = <error reading variable: Cannot access memory at address 0x28>, data = {{v_int = 1644333147, v_uint = 1644333147, v_long = 1644333147, v_ulong = 1644333147, v_int64 = 1644333147, v_uint64 = 1644333147, v_float = 6.01975544e+20, v_double = 8.1240851825072439e-315, v_pointer = 0x6202885b}, {v_int = 308920413, v_uint = 308920413, v_long = 140583178453085, v_ulong = 140583178453085, v_int64 = 140583178453085, v_uint64 = 140583178453085, v_float = 7.37589424e-28, v_double = 6.9457318856838656e-310, v_pointer = 0x7fdc1269c05d <_int_malloc+2845>}}}, {g_type = 0x0, data = {{v_int = 208, v_uint = 208, v_long = 208, v_ulong = 208, v_int64 = 208, v_uint64 = 208, v_float = 2.91470081e-43, v_double = 1.0276565433497928e-321, v_pointer = 0xd0}, {v_int = 4, v_uint = 4, v_long = 4, v_ulong = 4, v_int64 = 4, v_uint64 = 4, v_float = 5.60519386e-45, v_double = 1.9762625833649862e-323, v_pointer = 0x4}}}, {g_type = , data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 80, v_uint = 80, v_long = 80, v_ulong = 80, v_int64 = 80, v_uint64 = 80, v_float = 1.12103877e-43, v_double = 3.9525251667299724e-322, v_pointer = 0x50}}}, {g_type = , data = {{v_int = 118800, v_uint = 118800, v_long = 118800, v_ulong = 118800, v_int64 = 118800, v_uint64 = 118800, v_float = 1.66474258e-40, v_double = 5.8694998725940089e-319, v_pointer = 0x1d010}, {v_int = 310344832, v_uint = 310344832, v_long = 140583179877504, v_ulong = 140583179877504, v_int64 = 140583179877504, v_uint64 = 140583179877504, v_float = 8.06172704e-28, v_double = 6.9457319560595149e-310, v_pointer = 0x7fdc127f7c80 <main_arena>}}}, {g_type = , data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 308926953, v_uint = 308926953, v_long = 140583178459625, v_ulong = 140583178459625, v_int64 = 140583178459625, v_uint64 = 140583178459625, v_float = 7.37904314e-28, v_double = 6.9457318860069845e-310, v_pointer = 0x7fdc1269d9e9 <__libc_calloc+217>}}}}
        name = <optimized out>
        n_params = <optimized out>
        n_params_alloc = 16
        class = <optimized out>
        unref_class = <optimized out>
        object = <optimized out>
        __func__ = "g_object_new_valist"
#7  0x00007fdc12829afd in g_object_new (object_type=<optimized out>, first_property_name=<optimized out>) at ../gobject/gobject.c:1824
        object = <optimized out>
        var_args = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffdd7648800, reg_save_area = 0x7ffdd7648700}}
#8  0x00007fdbe7f8dd1d in panel_add_device (panel=0x55f234513620, device=0x55f2344f0510) at ../panels/network/cc-network-panel.c:676
        iter = {stamp = 0, user_data = 0x7fdc04ce8504 <g_ptr_array_maybe_expand+164>, user_data2 = 0x55f234513620, user_data3 = 0x55f2343ffba0}
        priv = 0x55f234513480
        device_g_type = Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str

#9  0x00007fdbe7f8de50 in manager_running (client=<optimized out>, pspec=<optimized out>, user_data=<optimized out>) at ../panels/network/cc-network-panel.c:998
        devices = 0x55f2343ffba0
        i = 1
        device_tmp = <optimized out>
        liststore_devices = <optimized out>
        selected = <optimized out>
        panel = 0x55f234513620
#10 0x00007fdc12817db0 in g_closure_invoke (closure=0x55f2346d3d90, return_value=0x0, n_param_values=1, param_values=0x7ffdd7648a30, invocation_hint=0x7ffdd76489b0) at ../gobject/gclosure.c:830
        marshal = 0x7fdc1281a0d0 <g_cclosure_marshal_VOID__VOID>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x55f2346d3d70
        __func__ = "g_closure_invoke"
#11 0x00007fdc128447a4 in signal_emit_unlocked_R.isra.0 (node=node@entry=0x55f2342056e0, detail=detail@entry=0, instance=instance@entry=0x55f234513620, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffdd7648a30) at ../gobject/gsignal.c:3814
        tmp = <optimized out>
        handler = 0x55f2346d4d00
        accumulator = 0x0
        emission = {next = 0x7ffdd7648dc0, instance = 0x55f234513620, ihint = {signal_id = 57, detail = 0, run_type = (G_SIGNAL_RUN_LAST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = 0x4 [None]}
        hlist = <optimized out>
        handler_list = 0x55f2346d4d00
        return_accu = 0x0
        accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 57
        max_sequential_handler_number = 1176
        return_value_altered = <optimized out>
#12 0x00007fdc12834a2e in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffdd7648be0) at ../gobject/gsignal.c:3496
        instance_and_params = 0x7ffdd7648a30
        signal_return_type = <optimized out>
        param_values = 0x7ffdd7648a48
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#13 0x00007fdc12834cb3 in g_signal_emit (instance=instance@entry=0x55f234513620, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3553
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffdd7648cc0, reg_save_area = 0x7ffdd7648c00}}
#14 0x00007fdc0296d0ba in gtk_widget_map (widget=0x55f234513620) at ../gtk/gtkwidget.c:5051
        priv = 0x55f234513530
        __func__ = "gtk_widget_map"
#15 0x00007fdc026d64b8 in gtk_box_forall (container=<optimized out>, include_internals=<optimized out>, callback=0x7fdc02728160 <gtk_container_map_child>, callback_data=0x0) at ../gtk/gtkbox.c:2678
        box = <optimized out>
        priv = 0x55f2342bd740
        child = <optimized out>
        children = 0x0
#16 0x00007fdc027281c3 in gtk_container_map (widget=0x55f2342bd870) at ../gtk/gtkcontainer.c:3697
#17 0x00007fdc12833d5b in _g_closure_invoke_va (param_types=<optimized out>, n_params=<optimized out>, args=0x7ffdd7648ec0, instance=<optimized out>, return_value=<optimized out>, closure=0x55f234205690) at ../gobject/gclosure.c:893
        marshal = <optimized out>
        marshal_data = <optimized out>
        in_marshal = <optimized out>
        real_closure = 0x55f234205670
        return_accu = <optimized out>
        accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = <optimized out>
        emission = Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
{next = 0x7ffdd76490a0, instance = 0x55f2342bd870, ihint = {signal_id = 57, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = }
        instance_type = <optimized out>
        emission_return = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = <optimized out>
        static_scope = <optimized out>
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#18 g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffdd7648ec0) at ../gobject/gsignal.c:3406
        return_accu = <optimized out>
        accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = <optimized out>
        emission = Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
{next = 0x7ffdd76490a0, instance = 0x55f2342bd870, ihint = {signal_id = 57, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = }
        instance_type = <optimized out>
        emission_return = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = <optimized out>
        static_scope = <optimized out>
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#19 0x00007fdc12834cb3 in g_signal_emit (instance=instance@entry=0x55f2342bd870, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3553
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffdd7648fa0, reg_save_area = 0x7ffdd7648ee0}}
#20 0x00007fdc0296d0ba in gtk_widget_map (widget=0x55f2342bd870) at ../gtk/gtkwidget.c:5051
        priv = 0x55f2342bd780
        __func__ = "gtk_widget_map"
```

**Comment by leigh123linux** [comment]
Thanks.
